### ISSUE TITLE
Calling createFetchAction with force: true breaks

### ISSUE THREAD

**Issue by androa** [vgno/redux-fetcher#14]
When calling `createFetchAction(id, url, { force: true })` it silently breaks completely. What happens is that the whole default options object is replaced, and method is no longer there. That in turn causes redux-api-middleware to not understand what is going on.

**Comment by wadim** [comment]
I saw this too but I just passed the method myself as a workaround. I agree, it should not replace the entire options object.

**Comment by androa** [comment]
It can be fixed by either merging the objects, or changing the function signature to `(id, url, { force = false, method = 'GET', body = '' } = {})`. Then each option will be just a locally available variable, instead of the options object.

**Comment by andreasrs** [comment]
Agree. Fix should be included in the next release.
